# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ea6279523868e00b16ea3bb650a4629fb7b5128d6c2021ac26debeb3e9fd807d8e128317a8b4202e6a989cf7cf77b101dfc89a69dd497ee3a96dca0dcaa50b2

test:
  secret_key_base: 20af5b071c170838fa486a970b222540a4b706988c2709144d389c4733a77e383eb1d5273d392fbedc4d7785bdaf6dc1ac5371ae936a3a5a824447aedb839dc0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
